from typing import Any, Dict, Protocol

class Logger(Protocol):
    def debug(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def bind(self, **kwargs: Any) -> "Logger": ...
    def warn(self, message: str, *args: Any, **kwargs: Any) -> None: ...
