"""State store interface definition."""
from typing import Optional, Protocol
from ..types import BotState, Trade

class StateStore(Protocol):
    """State persistence interface."""

    async def load_state(self) -> Optional[BotState]: ...
    async def save_state(self, state: BotState) -> None: ...
    async def append_trade(self, trade: Trade) -> None: ...
    async def get_trades(self) -> list[Trade]: ...

    # Conveniencia: lo que usa el resto del código
    async def get(self) -> BotState: ...
    async def set(self, state: BotState) -> None: ...