"""Core utilities module."""

from .candles import (
    body_percentage,
    candle_body,
    candle_range,
    count_streak,
    get_closes,
    get_highs,
    get_lows,
    get_opens,
    get_volumes,
    highest_high,
    is_doji,
    is_green,
    is_hammer,
    is_red,
    last,
    lower_wick,
    lowest_low,
    price_range,
    upper_wick,
    volume_avg,
)
from .features import (
    calculate_rsi,
    compute_features,
    feature_vector,
    normalize_features,
)
from .trend import (
    cluster_prices,
    identify_trend,
    is_breakout,
    linear_regression_slope,
    pivot_points,
    support_resistance_levels,
    trend_strength,
)

__all__ = [
    # Candles
    "body_percentage",
    "candle_body",
    "candle_range",
    "count_streak",
    "get_closes",
    "get_highs",
    "get_lows",
    "get_opens",
    "get_volumes",
    "highest_high",
    "is_doji",
    "is_green",
    "is_hammer",
    "is_red",
    "last",
    "lower_wick",
    "lowest_low",
    "price_range",
    "upper_wick",
    "volume_avg",
    # Features
    "calculate_rsi",
    "compute_features",
    "feature_vector",
    "normalize_features",
    # Trend
    "cluster_prices",
    "identify_trend",
    "is_breakout",
    "linear_regression_slope",
    "pivot_points",
    "support_resistance_levels",
    "trend_strength",
]
